<?php
/**
 * @var $block \Mirasvit\Giftr\Block\Item\Add
 */
?>

<div class="giftr-list" style="display: none"
     data-bind="scope: 'giftr-addto__form',
                mageInit: {
                'Magento_Ui/js/modal/modal':{
                'type': 'popup',
                'title': 'Choose your registry',
                'trigger': '[data-trigger=trigger]',
                'responsive': true,
                'buttons': []
                }}">

    <div class="registry-list" data-bind="visible: hasRegistries">
        <div class="registries" data-bind="foreach: registries">
            <label for="registry_>" class="label" data-bind="attr: { for: 'registry_' + value }">
                <input type="checkbox" id="registry_" name="registries[]" value=""
                       data-bind="checked: $parent.selected, value: value, attr: { id: 'registry_' + value }" />
                <span data-bind="text: label"></span>
            </label>
        </div>
        <a id="confirm-add-to-registry" href="#" data-bind="click: addProduct"><?= __('Add') ?></a>
    </div>

    <div data-bind="visible: isMessageVisible()">
        <span data-bind="html: getMessage()"></span>
    </div>
</div>


<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var popup = modal($('.giftr-list'));
        $(".togiftr").click(function() {
            $('.giftr-list').modal('openModal');
        });
    });
</script>
